# Site settings
title: Daniel McCarron
email: dan.mccarron@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of Daniel McCarron. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mccarrond 
github_username:  mccarrond

# Build settings
markdown: kramdown
